Repository 2024-Daegu-SW-Hackathon-For-U/Frontend, pull requests merged in 2024-09, with the labels that each got.

#3 공통 컴포넌트 구현
  package.json
  src/App.tsx
  src/api/instance/index.tsx
  src/styles/global/index.ts
Labels: ✨ Feature, 📦 Environment, 🎨 Design

#4 공통 컴포넌트 구현 및 기타 프로젝트 세팅
  package.json
  src/App.tsx
  src/api/instance/index.tsx
  src/styles/global/index.ts
Labels: 📦 Environment, 🎨 Design

#6 배포 파일 작성
  .github/workflows/deploy.yml
Labels: 🚀 Deploy

#9 Develop
  .eslintignore
  .eslintrc.json
  package.json
Labels: 🚀 Deploy

#16 Header UI 구현
  src/assets/header/menu.svg
  src/components/features/layout/header.tsx
Labels: ✨ Feature, 🎨 Design

#18 메인 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/images/SearchIcon.svg
  src/components/Home/Buttons.tsx
  src/components/Home/PlaceBox.tsx
  src/components/Home/Search.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature, 🎨 Design

#20 마이페이지 UI 구현
  src/pages/mypage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#21 헤더, 메인페이지, 마이페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/images/SearchIcon.svg
  src/assets/header/menu.svg
  src/components/Home/Buttons.tsx
  src/components/Home/PlaceBox.tsx
  src/components/Home/Search.tsx
  src/components/features/layout/header.tsx
  src/pages/home/index.tsx
  src/pages/mypage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🚀 Deploy

#23 메인페이지 오류 수정
  src/assets/home/SearchIcon.svg
  src/components/Home/Search.tsx
Labels: 😡 Bug Fix

#24 메인페이지 오류 수정
  src/assets/home/SearchIcon.svg
  src/components/Home/Search.tsx
Labels: 😡 Bug Fix, 🚀 Deploy

#25 라이브러리 버전 수정
  package.json
  pnpm-lock.yaml
  public/images/SearchIcon.svg
  src/components/Home/Search.tsx
Labels: 😡 Bug Fix

#26 메인페이지 오류 수정
  package.json
  pnpm-lock.yaml
  public/images/SearchIcon.svg
  src/components/Home/Search.tsx
Labels: 😡 Bug Fix

#28 메뉴바 구현
  src/components/features/layout/header.tsx
  src/components/features/layout/menu.tsx
  src/styles/global/index.ts
Labels: ✨ Feature, 🎨 Design

#32 아이콘 추가 및 메인 타이틀 수정
  index.html
  public/fire.png
  src/components/Home/Search.tsx
  src/pages/home/index.tsx
Labels: 📦 Environment, 🎨 Design

#33 기타 설정 및 ui 구현
  .github/workflows/deploy.yml
  .gitignore
  index.html
  public/fire.png
  src/api/.gitkeep
  src/api/instance/index.tsx
  src/components/Home/Search.tsx
  src/components/features/layout/header.tsx
  src/components/features/layout/menu.tsx
  src/constants/.gitkeep
  src/constants/URI.ts
  src/pages/home/index.tsx
  src/styles/global/index.ts
Labels: 🚀 Deploy

#36 추천 테마 지도 UI 구현
  index.html
  pnpm-lock.yaml
  src/assets/map/Add.svg
  src/assets/map/ArrowBackBlack.svg
  src/assets/map/ArrowBackWhite.svg
  src/components/RecommendMap/BackButton.tsx
  src/components/RecommendMap/PlusButton.tsx
  src/global.d.ts
  src/pages/recommendMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#38 develop->main
  index.html
  pnpm-lock.yaml
  src/assets/map/Add.svg
  src/assets/map/ArrowBackBlack.svg
  src/assets/map/ArrowBackWhite.svg
  src/components/RecommendMap/BackButton.tsx
  src/components/RecommendMap/PlusButton.tsx
  src/global.d.ts
  src/pages/recommendMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ➕Merge

#41 큐레이션 지도 UI
  src/components/Map/BackButton.tsx
  src/components/Map/MapListBox.tsx
  src/components/Map/PlusButton.tsx
  src/global.d.ts
  src/pages/curationMap/index.tsx
  src/pages/recommendMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#43 나의 지도 관리 페이지 UI 구현
  src/assets/my-map-setting/map-sample.jpg
  src/components/my-map-setting/curation-map/index.tsx
  src/components/my-map-setting/theme-map/index.tsx
  src/pages/my-map-setting/index.tsx
  src/pages/mypage/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 😡 Bug Fix

#45 add page UI 구현
  index.html
  package.json
  pnpm-lock.yaml
  src/components/Map/AddPlaceBox.tsx
  src/pages/addPlace/index.tsx
  src/pages/curationMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#49 Feat/issue #44
  src/components/features/layout/header.tsx
  src/components/features/layout/menu.tsx
  src/components/login/index.tsx
  src/hooks/DynamicNavigate/index.tsx
Labels: ✨ Feature, 🎨 Design

#55 api 호출 코드 구현
  src/api/hooks/auth/useGetLogin.ts
  src/api/hooks/comment/useDeleteComment.ts
  src/api/hooks/comment/useGetComment.ts
  src/api/hooks/comment/usePostComment.ts
  src/api/hooks/comment/usePutComment.ts
  src/api/hooks/map/useDeleteMap.ts
  src/api/hooks/map/useGetMap.ts
  src/api/hooks/map/usePostMap.ts
  src/api/instance/index.tsx
  src/pages/home/test.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 📡 API

#56 작업내용 정리
  index.html
  package.json
  pnpm-lock.yaml
  src/api/hooks/auth/useGetLogin.ts
  src/api/hooks/comment/useDeleteComment.ts
  src/api/hooks/comment/useGetComment.ts
  src/api/hooks/comment/usePostComment.ts
  src/api/hooks/comment/usePutComment.ts
  src/api/hooks/map/useDeleteMap.ts
  src/api/hooks/map/useGetMap.ts
  src/api/hooks/map/usePostMap.ts
  src/api/instance/index.tsx
  src/assets/header/kakao_symbol.svg
  src/assets/my-map-setting/map-sample.jpg
  src/components/Map/AddPlaceBox.tsx
  src/components/Map/BackButton.tsx
  src/components/Map/MapListBox.tsx
  src/components/features/layout/header.tsx
  src/components/features/layout/menu.tsx
  src/components/login/index.tsx
  src/components/my-map-setting/curation-map/index.tsx
  src/components/my-map-setting/theme-map/index.tsx
  src/hooks/DynamicNavigate/index.tsx
  src/pages/addPlace/index.tsx
  src/pages/curationMap/index.tsx
  src/pages/home/index.tsx
  src/pages/home/test.tsx
  src/pages/my-map-setting/index.tsx
  src/pages/mypage/index.tsx
  src/pages/recommendMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: 🚀 Deploy, 📡 API, ➕Merge

#57 eslint 오류 수정
  src/components/Map/AddPlaceBox.tsx
  src/routes/path.ts
Labels: 😡 Bug Fix

#58 prettier 오류 수정
  src/components/Map/AddPlaceBox.tsx
Labels: 😡 Bug Fix

#62 카카오 로그인 및 기타 기능 구현, 수정
  src/App.tsx
  src/api/hooks/auth/useGetLogin.ts
  src/api/hooks/auth/useKakaoLogin.ts
  src/api/hooks/map/useGetMap.ts
  src/api/hooks/place/useDeletePlace.ts
  src/api/hooks/place/useGetPlace.ts
  src/api/hooks/place/usePostPlace.ts
  src/components/login/index.tsx
  src/components/login/kakao-callback-page.tsx
  src/provider/auth/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/utils/storage/index.tsx
Labels: 😡 Bug Fix, ✨ Feature, 📡 API

#64 오류 수정
  src/pages/searchPlace/index.tsx
Labels: 😡 Bug Fix

#65 Feat: 페이지 이동 구현
  src/api/hooks/map/useGetMap.ts
  src/components/Home/PlaceBox.tsx
  src/pages/addPlace/index.tsx
  src/pages/curationMap/index.tsx
  src/pages/home/index.tsx
  src/pages/recommendMap/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature
